name: CODEOWNERS
on:
  push:
  pull_request:

jobs:
  run:
    name: Check Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: changed-files
        uses: tj-actions/changed-files@v35.6.1
      - uses: ./
        with:
          ignore-default: 'true'
          files: ${{ steps.changed-files.outputs.all_changed_files }}